#ifndef CONFIG_H
#define CONFIG_H

// Experiment Mode - PC
#define EXP_GEN_WORKLOAD 0
#define EXP_POWER_EVENT 1
#define EXP_TEST 2
// Experiment Mode - Power Supply
#define EXP_BASELINE 3
#define EXP_REPLAY 4
// UCx Mode
#define UCB_MODE_UCB0 5 // Needs hardware modification
#define UCB_MODE_UCB1 6
#define UCA_MODE_UCA3 7
// SPI Library Mode
#define SPI_MODE_DMA 8
#define SPI_MODE_BUSYPOLLING 9
// Rerank Mode
#define RERANK_MODE_LEA 10
#define RERANK_MODE_CPU_FULLVEC 11
#define RERANK_MODE_CPU_LONGPQ 20
// Searchlist Mode
#define SEARCHLIST_MODE_SORTED 12
#define SEARCHLIST_MODE_UNSORTED 13
// Prune Searchlist Mode
#define PRUNE_MODE_DISTANCE_ONLY 14
#define PRUNE_MODE_VISITED_FIRST 15
// IO/Compute Overlapping
#define OVERLAP_MODE_NONE 16
#define OVERLAP_MODE_ENABLE 17
// SPI Debug Mode
#define SPI_DEBUG_MODE_OFF 18
#define SPI_DEBUG_MODE_ON 19
// Quick 16 dim QPS profiling
#define QPS_PROFILE_MODE_LONG 21
#define QPS_PROFILE_MODE_SHORT 22
// Hardcap Iteration Limit
#define ITER_LIMIT_MODE_ON 23
#define ITER_LIMIT_MODE_OFF 24
// Correct Diskann implementation
#define CODE_MODE_DISKANN 25
#define CODE_MODE_ORIGINAL 26
// Partial Rerank Enable
#define PARTIAL_RERANK_MODE_ENABLE  27
#define PARTIAL_RERANK_MODE_NONE 28
// Early Termination Mode
#define EARLY_TERMINATION_MODE_OFF  29
#define EARLY_TERMINATION_MODE_ON 30
// Energy Wait Method
#define ENERGY_WAIT_METHOD_CALENDAR 32
#define ENERGY_WAIT_METHOD_RT1PS 33
#define ENERGY_WAIT_METHOD_OVERFLOW 34
#define RECHARGE_TIME_MS 100

#define EXPERIMENT      EXP_BASELINE
#define UCx_MODE        UCA_MODE_UCA3
#define SPI_MODE        SPI_MODE_DMA
#define RERANK_MODE     RERANK_MODE_LEA
#define SEARCHLIST_MODE SEARCHLIST_MODE_SORTED
#define PRUNE_MODE      PRUNE_MODE_DISTANCE_ONLY
#define OVERLAP_MODE    OVERLAP_MODE_NONE
#define SPI_DEBUG_MODE  SPI_DEBUG_MODE_ON
#define QPS_PROFILE_MODE QPS_PROFILE_MODE_SHORT
#define ITER_LIMIT_MODE ITER_LIMIT_MODE_OFF
#define CODE_MODE CODE_MODE_DISKANN
#define PARTIAL_RERANK_MODE PARTIAL_RERANK_MODE_NONE
#define EARLY_TERMINATION_MODE EARLY_TERMINATION_MODE_OFF
#define ENERGY_WAIT_METHOD ENERGY_WAIT_METHOD_OVERFLOW

#define PQ_PAGE_CACHE_COUNT 0
#define SAMPLE_RATE 0L // 0 to turnoff
#define STAT_TIME_MIN_MAX
#define STAT_FLASH_PROFILE

#define REPLAY_COUNT 100
#define VOLTAGE_GEAR_COUNT 6
#define VOLTAGE_WORKING_MIN 2.8f
#define VOLTAGE_WAIT_TRIGGER 2.8f
#define CAP_FARAD 0.0047f
#define SCALE_FACTOR 0.4f
#define ENERGY_PER_BYTE_UJ 0.079904f

/* Checkpoint */
#define CHECKPOINT_INTERVAL 800L
#if EXPERIMENT == EXP_POWER_EVENT
#define POWER_EVENT_ON
#endif
#define POWER_EVENT_INTERVAL 15

#endif
